### ISSUE TITLE
`npm run debug-ide` does not work with node v. 6.4.0

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/javascript-intro-to-debugging#10]
I think this is the issue at least. When running this lab in the Learn IDE (node v 6.4.0) I get the following error:

```
// :hearts: npm run debug-ide                                                    

> javascript-intro-to-debugging@0.1.0 debug-ide /home/aturkewi/code/labs/j
avascript-intro-to-debugging-v-000                                        
> ./bin/debug-ide                                                         

trap: SIGINT: bad trap                                                    
Debugger listening on [::]:5858                                           
Node Inspector v0.12.8                                                    
Visit http://104.236.196.127:36597/?port=5858 to start debugging.         
/home/aturkewi/code/labs/javascript-intro-to-debugging-v-000/node_modules/
node-inspector/lib/InjectorClient.js:111                                  
      cb(error, NM[0].ref);                                               
                     ^                                                    

TypeError: Cannot read property 'ref' of undefined                        
    at InjectorClient.<anonymous> (/home/aturkewi/code/labs/javascript-int
ro-to-debugging-v-000/node_modules/node-inspector/lib/InjectorClient.js:11
1:22)                                                                     
    at /home/aturkewi/code/labs/javascript-intro-to-debugging-v-000/node_m
odules/node-inspector/lib/DebuggerClient.js:121:7                         
    at Object.create.processResponse.value (/home/aturkewi/code/labs/javas
cript-intro-to-debugging-v-000/node_modules/node-inspector/lib/callback.js
:23:20)                                                                   
    at Debugger._processResponse (/home/aturkewi/code/labs/javascript-intr
o-to-debugging-v-000/node_modules/node-inspector/lib/debugger.js:95:21)   
    at Protocol.execute (_debugger.js:121:14)                             
    at emitOne (events.js:96:13)                                          
    at Socket.emit (events.js:188:7) 
    at readableAddChunk (_stream_readable.js:177:18)                      
    at Socket.Readable.push (_stream_readable.js:135:10)                  
    at TCP.onread (net.js:542:20)                                         
^C                                          
```

Looks like this issue: https://github.com/node-inspector/node-inspector/issues/905 which identifies upgrading to node 6.4.0 as the issue. 

Going to dig more into this tomorrow morning. 
Update script in bin? Add global install of `n` to the IDE so that students can downgrade for this lab?

tagging in @loganhasson to help track this issue

**Comment by aturkewi** [comment]
Closing this because the IDE is on 6.9.1
